# See http://www.appveyor.com/docs/appveyor-yml for many more options

build: false

# Set build info
environment: 
  environment: development
  version: 0.8.$(appveyor_build_number)
  
# Install prereqs
# install:
# - cinst pester

# Set alternative clone folder
clone_folder: c:\github\dbatools

artifacts:
  - path: msbuild.log
    name: MSBuild Log

before_test:
   # grab appveyor lab files
  - ps: .\Tests\appveyor.prep.ps1
   # "Get Pester manually"
  - ps: Install-Module -Name Pester -Repository PSGallery -Force | Out-Null
  # "Setting up the local SQL Server environments"
  - ps: .\Tests\appveyor.sqlserver.ps1
test_script:
  # "Installing nuget and PSScriptAnalyzer"
  #- ps: Install-PackageProvider NuGet -MinimumVersion '2.8.5.201' -Force | Out-Null
  #- ps: Import-PackageProvider NuGet -MinimumVersion '2.8.5.201' -Force | Out-Null
  - ps: Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.6.0 -Repository PSGallery -Force | Out-Null
  - vstest.console /logger:Appveyor bin\projects\dbatools\dbatools.Tests\bin\Debug\dbatools.Tests.dll
  # "Test with native PS version"
  - ps: .\Tests\appveyor.pester.ps1
  
  # "Test with PS version 3" - Removed because it's not a true test. Even PS4+ .Where() works
  # - ps: powershell.exe -version 3.0 -executionpolicy bypass -noprofile -file .\Tests\appveyor.pester.ps1

  # "Collecting and uploading results"
  - ps: .\Tests\appveyor.pester.ps1 -Finalize

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))